[package]
name = "travelling_ant"
version = "0.3.1"
edition = "2021"
authors = ["Alix Bernard"]
description = "Short program allowing to solve the travelling ant problem."
license = "MIT"
readme = "README.md"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
